# Generated by Django 2.0 on 2019-03-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='image',
            field=models.ImageField(blank=True, upload_to='org/%Y/%m', verbose_name='封面图'),
        ),
    ]
