# Generated by Django 2.0 on 2019-03-23 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_courseorg_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='tag',
            new_name='type',
        ),
    ]
