# Generated by Django 2.0 on 2019-03-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20190319_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='时间'),
        ),
    ]
