# Generated by Django 2.0 on 2019-03-22 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_usermessage_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessage',
            name='time',
        ),
    ]
