# Generated by Django 2.0 on 2019-03-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_usermessage_user_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessage',
            name='user',
        ),
        migrations.AddField(
            model_name='usermessage',
            name='user_id',
            field=models.IntegerField(default=0, verbose_name='接收用户的 id'),
        ),
    ]
