# Generated by Django 2.0 on 2019-03-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20190319_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='url',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='访问地址'),
        ),
    ]
