# Generated by Django 2.0 on 2019-03-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_lesson_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_time',
            field=models.IntegerField(default=0, verbose_name='视频时长'),
        ),
    ]
