# Generated by Django 2.0 on 2019-03-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20190319_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/video/%Y/%m', verbose_name='视频封面'),
        ),
    ]
